# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aadf427cfd9982f56d140588d074d458723ea8993e5c81f761e4efd87fbd0e7d23ba212371d921c125e55d58cf7c124a400ff286f7f8d479c9292a42cef0a0b0

test:
  secret_key_base: b162d2a273e68b0c8a9f10e09d67fd6ee31dadab900e81c8a0f865fdba62bfb9453ae4af4bf89e08b1f49f904a0f6449c14ca91ce9ea586a8157b88f13fe96e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
